New Test Cases related to labeling of Graph elements
scania/sdos-orchestration-flow-designer pull request #26
Opened 2024-08-12 07:01 UTC by Adij1110

-New Test Cases related to labeling of Graph elements
-Generalized way to add elements

2024-08-13 09:06 UTC, Abdulazeem84 commented
Functional test cases have reviewed and look good.

2024-08-13 13:36 UTC, abhishekkundu25 requested changes

2024-08-13 13:36 UTC, abhishekkundu25 commented on cypress/support/commands.ts
> +      .then(() => console.log("drop"));
why are the console logs needed here?

2024-08-14 08:13 UTC, abhishekkundu25 approved these changes

2024-08-14 08:16 UTC, merged